---

- include: install.yml

- name: ensure database service is up
  service:
    name: postgresql
    state: started
  become: yes

- include: users.yml
  when: "'postgresql_master' in group_names"

- include: configure.yml
  when: "'postgresql_master' in group_names"

- name: make {{ app_name }} database
  postgresql_db:
    name: "{{ app_name }}"
    state: present
    login_user: postgres
  when: "'postgresql_master' in group_names"
  become_user: postgres
  become: yes

- include: standby.yml
  when: "'postgresql_standby' in group_names"
